language: node_js

sudo: false

node_js:
- '6.9.1'
- stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  firefox: 'latest'

env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: ???

before_install:
- npm install -g pr-bumper@^3.0.0

install:
- npm install

before_script:
- npm run build
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

after_success:

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: ???
  on:
    all_branches: true
    node: '6.9.1'
    tags: true
